name: Download and Upload to Huawei OBS

on:
  push:
    branches: 
      - main

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download a 50MB file
        run: |
          # 下载一个50MB的文件，用于测试
          wget http://hkg.download.datapacket.com/100mb.bin -O test_file.bin

      - name: Install obsutil
        run: |
          # 下载适合系统架构的 obsutil 工具
          wget https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz
          # 解压安装包
          tar -xzvf obsutil_linux_amd64.tar.gz
          # 设置可执行权限
          chmod 755 obsutil
          # 验证安装是否成功
          ./obsutil version

      - name: Upload file to Huawei OBS
        env:
          OBS_AK: ${{ secrets.OBS_AK }}
          OBS_SK: ${{ secrets.OBS_SK }}
          OBS_ENDPOINT: ${{ secrets.OBS_ENDPOINT }}
          OBS_BUCKET: ${{ secrets.OBS_BUCKET }}
        run: |
          # 配置 obsutil
          ./obsutil config -i $OBS_AK -k $OBS_SK -e $OBS_ENDPOINT
          # 上传文件到 OBS 存储桶
          ./obsutil cp test_file.bin obs://$OBS_BUCKET/test_file.bin

      - name: Clean up
        run: |
          # 删除测试文件
          rm -f test_file.bin
